In [495]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)

## The Patient Data
Sex: M = Male, F = Female

Occupation : FT = Working Full Time, PT = Working Part Time, NW = Not Working

SmartPhone : 0 = Does not have Smart Phone, 1 = Has Smart Phone

In [518]:
#The patient data and preferences
patientData = pd.read_excel("D:\Luka.xlsx")
patientData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106 entries, 0 to 105
Data columns (total 21 columns):
Patient_ID            106 non-null object
Age                   106 non-null int64
Sex                   106 non-null object
Occupation            106 non-null object
SmartPhone            106 non-null int64
CommunicationStyle    106 non-null object
SubjectMatter1        106 non-null object
SubjectMatter2        76 non-null object
SubjectMatter3        41 non-null object
Video                 0 non-null float64
Image                 0 non-null float64
Article               0 non-null float64
Text                  0 non-null float64
MedRem                0 non-null float64
Info                  0 non-null float64
Motivation            0 non-null float64
Checkup               0 non-null float64
MedRem_Count          0 non-null float64
Info_Count            0 non-null float64
Motivation_Count      0 non-null float64
Checkup_Count         0 non-null float64
dtypes: float64(12), int64(2), object(7)
memory usage: 17.5+ KB

In [519]:
patientData.head()

,Patient_ID,Age,Sex,Occupation,SmartPhone,CommunicationStyle,SubjectMatter1,SubjectMatter2,SubjectMatter3,Video,Image,Article,Text,MedRem,Info,Motivation,Checkup,MedRem_Count,Info_Count,Motivation_Count,Checkup_Count
0,A001,83,F,NW,1,Rational,Cholesterol,Dialysis,BP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A002,55,M,NW,1,Relational,Cholesterol,Dialysis,BP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A003,78,F,NW,1,Individual,Diabetis,BP,Cholesterol,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,A004,81,M,NW,1,Individual,Cholesterol,Dialysis,BP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,A005,65,F,NW,1,Emotional,Dialysis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## CommunicationStyle 
referes to communication styles of patients and their score with respect to the media type , higher score indicates more facorable. Example Emotional, like video form of communication more

In [426]:
CommunicationStyle = pd.DataFrame.from_items([('Emotional',[0.5,0.25,0.15,0.1]),
                          ('Relational', [0.1,0.5,0.2,0.2]),
                         ('Individual', [0.2,0.2,0.5,0.1]),
                         ('Rational', [0.1,0.2,0.2,0.5])], orient='index', columns = ['Video','Image','Article','Text'])
CommunicationStyle

            Video  Image  Article  Text
Emotional     0.5   0.25     0.15   0.1
Relational    0.1   0.50     0.20   0.2
Individual    0.2   0.20     0.50   0.1
Rational      0.1   0.20     0.20   0.5

## Subject Matter
1 indicates requires form of communication , 0 indicated does not require that form of communication
MedRem = Medication Reminder
info = General Information
Motivation = Motivational Content
Checkup = Checkup / Appointment reminders

In [427]:
SubjectMatter = pd.DataFrame.from_items([('MedRem',[1,1,1,1]),
                                       ('Info', [1,1,1,1]),
                                       ('Motivation', [1,1,1,1]),
                                       ('Checkup', [0,0,0,1])],orient='index', columns = ['BP','Cholesterol','Diabetis','Dialysis'])
SubjectMatter

            BP  Cholesterol  Diabetis  Dialysis
MedRem       1            1         1         1
Info         1            1         1         1
Motivation   1            1         1         1
Checkup      0            0         0         1

## Preference of Media type by Age Groups
3 Age groups, under 35, 35 to 60 and 60+

In [520]:
AgePref = pd.DataFrame.from_items([('U35',[0.4,0.15,0.1,0.35]),
                              ('U60', [0.3,0.2,0.4,0.1]),
                             ('O60', [0.2,0.1,0.5,0.2])], orient='index', columns = ['Video','Image','Article','Text'])
AgePref

     Video  Image  Article  Text
U35    0.4   0.15      0.1  0.35
U60    0.3   0.20      0.4  0.10
O60    0.2   0.10      0.5  0.20

## Preference of Media type by Occupation
FT = Working Full Time
PT = Working Part Time
NW = not working

In [311]:
OccuPref = pd.DataFrame.from_items([('FT',[0.1,0.35,0.15,0.4]),
                          ('PT', [0.3,0.2,0.4,0.1]),
                         ('NW', [0.5,0.2,0.1,0.2])], orient='index', columns = ['Video','Image','Article','Text'])
OccuPref

    Video  Image  Article  Text
FT    0.1   0.35     0.15   0.4
PT    0.3   0.20     0.40   0.1
NW    0.5   0.20     0.10   0.2

## CommunicationType
MedRem = Medication Reminder, Info = Informational Media, Motivation = Motivational Media, Checkup = Checkup/ appointment setup reminder
The communication type fields are marked with "1" if the media type is allowed for that category, "0" if it is not. For example a medication reminder cannot be in a video form so it will have a value 0

In [312]:
CommunicationType = pd.DataFrame.from_items([('MedRem',[0,1,0,1]),
                          ('Info', [1,1,1,1]),
                         ('Motivation', [1,1,1,1]),
                         ('Checkup', [0,0,0,1])], orient='index', columns = ['Video','Image','Article','Text'])
CommunicationType

            Video  Image  Article  Text
MedRem          0      1        0     1
Info            1      1        1     1
Motivation      1      1        1     1
Checkup         0      0        0     1

## CommunicationFrequency 
The number of reminders that need to be sent in the given time period. M = Monthly, W = Weekly, D = Daily

In [313]:
#Dataframes are created for CommunicationStyle, CommunicationType, CommunicationFrequency and the respectives scores / values are filled in the dataframes  

CommunicationFrequency = pd.DataFrame.from_items([('BP',['W','M','M','W']),
                          ('Diabetis', ['D','W','M','W']),
                         ('Cholesterol', ['W','W','M','M']),
                         ('Dialysis', ['D','M','W','W'])], orient='index', columns = ['Video','Image','Article','Text'])

CommunicationFrequency

            Video Image Article Text
BP              W     M       M    W
Diabetis        D     W       M    W
Cholesterol     W     W       M    M
Dialysis        D     M       W    W

In [429]:
def AgePrefFunc(age,media): #assigns score for different media types based on age
    ageWeightage = 25
    
    if age <= 35 :
        AgeVideo = AgePref.loc['U35']['Video'] *ageWeightage
        AgeImage = AgePref.loc['U35']['Image'] *ageWeightage
        AgeArticle = AgePref.loc['U35']['Article'] *ageWeightage
        AgeText = AgePref.loc['U35']['Text'] *ageWeightage
    elif age <= 60 :
        AgeVideo = AgePref.loc['U60']['Video'] *ageWeightage
        AgeImage = AgePref.loc['U60']['Image'] *ageWeightage
        AgeArticle = AgePref.loc['U60']['Article'] *ageWeightage
        AgeText = AgePref.loc['U60']['Text'] *ageWeightage
    else :
        AgeVideo = AgePref.loc['O60']['Video'] *ageWeightage
        AgeImage = AgePref.loc['O60']['Image'] *ageWeightage
        AgeArticle = AgePref.loc['O60']['Article'] *ageWeightage
        AgeText = AgePref.loc['O60']['Text'] *ageWeightage
        
    if media == "Video" :
        return AgeVideo
    elif media == "Image" :
        return AgeImage 
    elif media == "Text" :
        return AgeText
    elif media == "Article" :
        return AgeArticle
    
def OccupationPrefFunc(x,media): #assigns score for different media types based on Occupation
    occupation = x
    OccuWeightage = 15

    OccuVideo = OccuPref.loc[occupation]['Video'] * OccuWeightage
    OccuImage = OccuPref.loc[occupation]['Image'] * OccuWeightage
    OccuArticle = OccuPref.loc[occupation]['Article'] * OccuWeightage
    OccuText = OccuPref.loc[occupation]['Text'] * OccuWeightage
    
    if media == "Video" :
        return OccuVideo
    elif media == "Image" :
        return OccuImage 
    elif media == "Text" :
        return OccuText
    elif media == "Article" :
        return OccuArticle
    
def CommStyleFunc(x,media): #assigns score for different media types based on Communication
    CommStyle = x      
    CommWeightage = 60
    CommStyleVideo = CommunicationStyle.loc[CommStyle]['Video'] * CommWeightage
    CommStyleImage = CommunicationStyle.loc[CommStyle]['Image'] * CommWeightage
    CommStyleArticle = CommunicationStyle.loc[CommStyle]['Article'] * CommWeightage
    CommStyleText = CommunicationStyle.loc[CommStyle]['Text'] * CommWeightage
    
    if media == "Video" :
        return CommStyleVideo
    elif media == "Image" :
        return CommStyleImage 
    elif media == "Text" :
        return CommStyleText
    elif media == "Article" :
        return CommStyleArticle

In [516]:
def AllocateMediaScore():
    for media in ['Video','Image','Article','Text']:
        patientData[media] = ( patientData['Age'].apply(AgePrefFunc,args = (media,))
                             + patientData['Occupation'].apply(OccupationPrefFunc,args = (media,))
                             + patientData['CommunicationStyle'].apply(CommStyleFunc,args = (media,)))

    patientData['Video'] = patientData['SmartPhone'] * patientData['Video']
    patientData['Image'] = patientData['SmartPhone'] * patientData['Image']
    patientData['Article'] = patientData['SmartPhone'] * patientData['Article']
    
    dump = patientData.ix[:,9:13]    
    patientData['test']= [list(dump.columns[np.argsort(list(type)[1: ])]) for type in list(dump.to_records())]

In [504]:
def AllocateMediaType(media,communication):
    for i in range (-1,-(len(media)+1),-1) :
        if CommunicationType.loc[communication][media[i]] == 1 :
            return (media[i])
            break

In [505]:
def WriteAllocatedMediaType():
    for communication in ['MedRem','Info','Motivation','Checkup']:
       patientData[communication] = patientData['test'].apply(AllocateMediaType,args = (communication,))

In [517]:
if __name__ == '__main__' :
    AllocateMediaScore()
    WriteAllocatedMediaType()
    
patientData.head()

,Patient_ID,Age,Sex,Occupation,SmartPhone,CommunicationStyle,SubjectMatter1,SubjectMatter2,SubjectMatter3,Video,Image,Article,Text,MedRem,Info,Motivation,Checkup,MedRem_Count,Info_Count,Motivation_Count,Checkup_Count,PreffMedia,test
0,A001,83,F,NW,1,Rational,Cholesterol,Dialysis,BP,18.0,17.0,30.0,35.0,Text,Text,Text,Text,NaN,NaN,NaN,NaN,Text,"[Image, Video, Article, Text]"
1,A002,55,M,NW,1,Relational,Cholesterol,Dialysis,BP,24.0,35.0,24.0,17.0,Image,Image,Image,Text,NaN,NaN,NaN,NaN,Image,"[Text, Video, Article, Image]"
2,A003,78,F,NW,1,Individual,Diabetis,BP,Cholesterol,23.0,17.0,45.0,15.0,Image,Article,Article,Text,NaN,NaN,NaN,NaN,Article,"[Text, Image, Video, Article]"
3,A004,81,M,NW,1,Individual,Cholesterol,Dialysis,BP,23.0,17.0,45.0,15.0,Image,Article,Article,Text,NaN,NaN,NaN,NaN,Article,"[Text, Image, Video, Article]"
4,A005,65,F,NW,1,Emotional,Dialysis,NaN,NaN,38.0,19.5,27.5,15.0,Image,Video,Video,Text,NaN,NaN,NaN,NaN,Video,"[Text, Image, Article, Video]"